### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute '__version__'

### ISSUE THREAD

**Issue by qusai-gazawy** [pythonlessons/background_removal#5]
To save the .onnx faceNet model in my models folder, I tried running convert_to_onnx.py and I get this error:

`Traceback (most recent call last):
  File "C:\Users\Cando\Desktop\FaceRec_Denem99\faceNet\convert_to_onnx.py", line 3, in <module>
    import tf2onnx
  File "C:\Python310\lib\site-packages\tf2onnx\__init__.py", line 10, in <module>
    from . import verbose_logging as logging
  File "C:\Python310\lib\site-packages\tf2onnx\verbose_logging.py", line 15, in <module>
    TF2 = tf.__version__.startswith("2.")
AttributeError: module 'tensorflow' has no attribute '__version__`

I tried reinstalling tensorflow, tf2onnx but still doesn't work

**Comment by pythonlessons** [comment]
what version did you install? try to install tensorflow==2.10.*
